'?':
    value: false
_wandb:
    value:
        cli_version: 0.22.1
        e:
            pl62g5idh66po5quyosfzcg0ndsi5izy:
                codePath: test.py
                codePathLocal: test.py
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "99882598400"
                        used: "47804313600"
                email: tcx513887573@gmail.com
                executable: /home/ka/ka_anthropomatik/ka_et4232/miniconda3/envs/py10/bin/python
                git:
                    commit: 71325b24f7112066c193c299322209c648e7335d
                    remote: git@github.com:anyRandomHuman/BRC_tcx.git
                gpu: NVIDIA A100-PCIE-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-64bde0de-090a-2cf9-15d0-b66efa085198
                host: uc2n572.localdomain
                memory:
                    total: "405398986752"
                os: Linux-5.14.0-427.50.1.el9_4.x86_64-x86_64-with-glibc2.34
                program: /pfs/data6/home/ka/ka_anthropomatik/ka_et4232/workspace/BRC_tcx/test.py
                python: CPython 3.10.18
                root: /pfs/data6/home/ka/ka_anthropomatik/ka_et4232/workspace/BRC_tcx
                slurm:
                    cluster_name: uc3
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "24"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: ka
                    job_cpus_per_node: "24"
                    job_end_time: "1759955634"
                    job_gid: "44355"
                    job_gpus: "0"
                    job_id: "1726126"
                    job_name: test.sh
                    job_nodelist: uc2n572
                    job_num_nodes: "1"
                    job_partition: gpu_a100_short
                    job_qos: normal
                    job_start_time: "1759955034"
                    job_uid: "507685"
                    job_user: ka_et4232
                    jobid: "1726126"
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: uc2n572
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /pfs/data6/home/ka/ka_anthropomatik/ka_et4232/workspace/BRC_tcx
                    submit_host: uc3n991.localdomain
                    task_pid: "284820"
                    tasks_per_node: "24"
                    topology_addr: VirtualInterconnnect..uc2ibbi2.uc2n572
                    topology_addr_pattern: switch.switch.switch.node
                startedAt: "2025-10-08T20:24:44.073615Z"
                writerId: pl62g5idh66po5quyosfzcg0ndsi5izy
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 12
                - 45
            "2":
                - 1
                - 12
                - 45
            "3":
                - 13
                - 16
            "4": 3.10.18
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
alsologtostderr:
    value: false
batch_size:
    value: 100
chex_assert_multiple_cpu_devices:
    value: false
chex_n_cpu_devices:
    value: 1
chex_skip_pmap_variant_if_single_device:
    value: true
env_names:
    value: HB_NOHANDS
eval_episodes:
    value: 10
eval_interval:
    value: 600
help:
    value: false
helpfull:
    value: false
helpshort:
    value: false
helpxml:
    value: false
log_dir:
    value: ""
log_to_wandb:
    value: true
logtostderr:
    value: false
max_steps:
    value: 100
offline_evaluation:
    value: true
only_check_args:
    value: false
pdb:
    value: false
pdb_post_mortem:
    value: false
profile_file:
    value: null
pymjcf_debug:
    value: false
pymjcf_debug_full_dump_dir:
    value: ""
pymjcf_log_xml:
    value: false
render:
    value: false
replay_buffer_size:
    value: 100
run_with_pdb:
    value: false
run_with_profiling:
    value: false
seed:
    value: 0
showprefixforinfo:
    value: true
start_training:
    value: 50
stderrthreshold:
    value: fatal
test_random_seed:
    value: 301
test_randomize_ordering_seed:
    value: ""
test_srcdir:
    value: ""
test_tmpdir:
    value: /scratch/slurm_tmpdir/job_1726126/absl_testing
timeout:
    value: true
updates_per_step:
    value: 2
use_cprofile_for_profiling:
    value: true
v:
    value: 0
verbosity:
    value: 0
width_critic:
    value: 2
xml_output_file:
    value: ""
